export default [
	'in a bustling neon-lit cyberpunk city at midnight',
	'on a serene beach during a vibrant sunset',
	'in a mystical enchanted forest filled with glowing flora',
	'on the surface of a distant, alien planet with purple skies',
	'in a steampunk metropolis with intricate clockwork mechanisms',
	'inside a futuristic space station orbiting a blue giant',
	'on a windswept desert under a burning, golden sun',
	'in a cozy mountain cabin surrounded by snow-capped peaks',
	'within a hidden underwater city made of coral and glass',
	'in a vibrant, surreal dreamscape of floating islands and rainbow skies',
	'on a post-apocalyptic wasteland with scattered remnants of civilization',
	'in a sprawling metropolis where ancient traditions meet modern tech',
	'on a quaint European street during a gentle autumn rain',
	'in a bustling marketplace in a lively Moroccan medina',
	'within a magical library where books come to life',
	'in a vast, empty plain under a sky swirling with auroras',
	'on a remote volcanic island with glowing lava flows',
	'in a modern art museum with interactive digital exhibits',
	'at a high-tech research lab brimming with futuristic gadgets',
	'in an ancient temple hidden deep in a lush tropical jungle',
	'on a quiet suburban street during a crisp winter evening',
	'in a vibrant festival setting with colorful banners and lively music',
	'on a foggy moor with mysterious, whispering winds',
	'in a secret garden filled with exotic, rare blooms',
	'within a cavern lit by bioluminescent fungi',
	'in a medieval castle during a lively royal banquet',
	'at a busy spaceport where starships dock and depart',
	'in a sprawling urban park framed by a city skyline',
	'in a quiet Zen garden with raked sand and serene ponds',
	'on a remote Antarctic research base surrounded by endless ice',
	'in a high-energy dance club with pulsing lights and booming beats',
	'in a secluded monastery perched atop a misty mountain',
	'at a futuristic sports arena hosting an epic showdown',
	'in a vibrant underwater reef teeming with colorful life',
	'in a dreamy countryside dotted with rolling green hills and wildflowers',
	'within an old Victorian mansion hiding countless secrets',
	'in a dynamic sports stadium filled with cheering fans',
	'on a scenic lakeside during a peaceful twilight',
	'in a futuristic, robot-run city with holographic billboards',
	'in a magical ice palace shimmering with crystalline frost',
	'at a bustling train station on a rainy afternoon',
	'within a neon-drenched street market in an urban jungle',
	'in a quiet, rustic barn surrounded by golden fields',
	'on the deck of a majestic cruise ship sailing a sparkling ocean',
	'at a high-altitude observatory offering a breathtaking cosmic view',
	'at a lively carnival bursting with colorful rides and games',
	'in a grand opera house adorned with ornate, historic architecture',
	'on a futuristic space colony on Mars with vast red landscapes',
	'in a secret hideout tucked away beneath a modern city',
	'in a sunlit vineyard nestled in the rolling hills of Tuscany',
	'at an abandoned amusement park with eerie, silent rides',
	'in a serene meadow where wild butterflies flutter freely',
	'amid a cosmic nebula with swirling interstellar gases',
	'on a rainy street corner in a vibrant urban neighborhood',
	'in a lush, tropical rainforest with cascading waterfalls',
	'at a tranquil lake reflecting the soft hues of the sky',
	'in a bustling harbor city alive with ships and busy docks',
	'on a remote, windswept plateau with endless panoramic views',
	'in a mysterious enchanted castle floating high in the sky',
	'on a surreal lunar landscape with deep craters and dusty plains',
	'under the big top of an elaborate circus lit by starlight',
	'in a bustling open-air bazaar filled with exotic aromas',
	'on a bright, cheerful farm with sprawling fields and red barns',
	'in a futuristic laboratory featuring advanced AI systems',
	'at a vibrant music festival with live bands and spectacular lights',
	'in a quaint fishing village along a rugged, rocky coastline',
	'in a fantastical realm inhabited by dragons and magical beings',
	'at a chic rooftop bar overlooking a glowing, modern cityscape',
	'in an urban park transformed by interactive public art installations',
	'next to an ancient ruin boldly contrasted with modern graffiti',
	'on a high-speed, futuristic highway racing above neon-lit roads',
	'in a rustic café filled with vintage decor and soft jazz melodies',
	'within a secret cave studded with hidden, sparkling crystals',
	'at a majestic waterfall enveloped by a dense, green forest',
	'in a surreal landscape where the laws of gravity bend',
	'on a neon-drenched street deep in a cyber metropolis',
	'at a bustling science fair showcasing interactive inventions',
	'in a mystical valley blanketed by early morning fog',
	'on a futuristic space elevator soaring above the clouds',
	'in a serene garden of sculpted topiaries and tranquil ponds',
	'in a hidden alcove of an ancient library brimming with lore',
	'at a vibrant nightclub alive with live DJ performances',
	'on a peaceful hillside dotted with fields of lavender',
	'in a grand ballroom adorned with opulent chandeliers and gilded details',
	'aboard a serene riverboat gliding through misty waters',
	'in a mystical desert with towering sand dunes and secret oases',
	'at a dynamic street art festival in a trendy urban district',
	'inside a high-tech smart home with futuristic interfaces',
	'in an enchanted meadow where delicate fairies dance',
	'at a retro diner pulsing with neon lights and vintage tunes',
	'across a vast, open plain lit by a breathtaking sunset',
	'under the deep blue sea amid a vibrant coral reef',
	'on a rocky mountainside with sweeping, panoramic views',
	'in a bustling space bazaar at a distant intergalactic outpost',
	'at a magical fairground where wonders defy the laws of physics',
	'inside a trendy co-working space with cutting-edge design',
	'on a sprawling rooftop garden amidst a concrete jungle',
	'in a secluded mountain valley with a crystal-clear stream',
	'within a futuristic megacity of soaring skyscrapers and flying cars',
	'in a timeless fairy tale village with charming cobblestone streets',
	'at a cutting-edge virtual reality arcade filled with immersive worlds',
	'in a sun-drenched plaza set in a picturesque Mediterranean town',
	'inside a mystical sanctuary lit by floating lanterns',
	'at a scenic overlook with a panoramic view of a sparkling city',
	'in a lively urban marketplace celebrating diverse cultures',
	'within a pastel-hued wonderland of cotton candy clouds',
	'in a tranquil garden maze with towering hedges and secret paths',
	'on a windswept coastal bluff where waves crash below',
	'at a serene yoga retreat nestled in a quiet mountain setting',
	'in a whimsical, cartoon-like town filled with quirky characters',
	'in a dynamic city square featuring bold modern art installations',
	'aboard a futuristic monorail gliding over bustling streets',
	'at a secluded eco-village embraced by pristine nature',
	'inside a vibrant modern mall alive with diverse storefronts',
	'in a quaint, historical district with centuries-old architecture',
	'in an industrial loft boasting exposed brick and vintage style',
	'in a quiet riverside park shaded by gracefully swaying willows',
	'at a lively street fair bursting with life, color, and music',
	'by a serene, secluded bay where gentle waves lap the shore'
];
